Footer editable fields & separation
lumberdev/atelier pull request #112
Opened 2024-05-01 14:00 UTC by slee288

### WHAT IT DOES:

- Add editable fields on Atelier admin for footer
- Separate campaign footer from the global footer

### WHAT TO TEST:

- [ ] On Atelier **Settings** tab, go to the section **Store Footer** to edit the footer links or footer background color.
- [ ] Go to any campaign page, and check if the settings have been applied on the footer.
- [ ] Go to the root website (no subdomain), and check if the global footer remains the same

### PREVIEW:

- Store Footer fields

![image](https://github.com/lumberdev/atelier/assets/43429460/f8f15294-92e4-4672-a019-4aff19f02c68)

- Global footer

![image](https://github.com/lumberdev/atelier/assets/43429460/d4d955a0-cf43-447e-8a2c-315cd2e1d822)

- Campaign footer

![image](https://github.com/lumberdev/atelier/assets/43429460/0d0d3959-ae72-4cbd-9ab6-cd7393520bb1)

2024-05-01 15:44 UTC, pratikmdhr requested changes

2024-05-01 15:44 UTC, pratikmdhr commented on components/atelier-landing-page/Footer/index.tsx
> +  ) : (
we should probably keep the store related code separate from our atelier.sale landing page. Currently the components inside `atelier-landing-page` only includes the code for our landing page which is controlled by Tina CMS.

We could probably create a new footer component inside `campaign`?

2024-05-01 15:48 UTC, slee288 commented on components/atelier-landing-page/Footer/index.tsx
> +  ) : (
now I think about it I think this solution might be better, so should I separate it inside `campaign` directory?

2024-05-01 16:00 UTC, pratikmdhr commented on components/atelier-landing-page/Footer/index.tsx
> +  ) : (
hmm are also planning to add a separate landing page for each store?

2024-05-01 16:00 UTC, pratikmdhr commented on components/atelier-landing-page/Footer/index.tsx
> +  ) : (
actually lets huddle lol

2024-05-02 19:47 UTC, slee288 commented on components/atelier-landing-page/Footer/index.tsx
> +  ) : (
@pratikmdhr I separated the footer on different directories - let me know if you have a chance to review it

2024-05-03 14:04 UTC, pratikmdhr approved these changes
looks good ! ✅

2024-05-03 14:16 UTC, merged